name: GoHive
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  intl_phone_number_input: ^0.7.3
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  image_picker: ^1.0.7
  video_player: ^2.8.6
  dio: ^5.4.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  universal_io: ^2.2.2
  flutter_launcher_icons: ^0.14.1
  cached_network_image: ^3.3.1
  loading_overlay: ^0.4.2
  like_button: ^2.0.0
  timeago: ^3.3.0
  ionicons: ^0.2.0
  animations: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_background.png
    - assets/facebook_icon.png
    - assets/google_icon.png
    - assets/apple_icon.png
    - assets/email_icon.png
    - assets/images/home.png
    - assets/images/search.png
    - assets/images/add.png
    - assets/images/profile.png
    - assets/images/ai_mentor.png
    - assets/age_icon.png
    - assets/phone_icon.png
    - assets/password_icon.png
    - assets/images/messages_icon.png
    - assets/images/filter_icon.png
    - assets/images/default_avatar.png
    - assets/images/tidy_challenge.png
    - assets/images/moon_challenge.png
    - assets/images/animal_challenge.png
    - assets/images/dance_challenge.png