name: a2bpoint
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  intl_phone_number_input: ^0.7.3
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  intl: ^0.18.0  # Add this line for intl package
  image_picker: ^1.0.0
  shared_preferences: ^2.2.2
  universal_io: ^2.2.0
  flutter_launcher_icons: ^0.14.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_background.png
    - assets/facebook_icon.png
    - assets/google_icon.png
    - assets/apple_icon.png
    - assets/email_icon.png
    - assets/images/home.png
    - assets/images/search.png
    - assets/images/add.png
    - assets/images/profile.png
    - assets/images/ai_mentor.png
    - assets/age_icon.png
    - assets/phone_icon.png
    - assets/password_icon.png
    - assets/images/messages_icon.png
    - assets/images/filter_icon.png
